sudo: false

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

addons:
  postgresql: "9.4"
  sonarcloud:
    organization: "suminb-github"

services:
  - postgresql

env:
  global:
    - DB_URL="postgres:///finance"
    - TEST_DB_URL="postgres:///finance"
    - PYTHONPATH=.

stages:
  - type checking
  - test

install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - pip install -e .

script:
    - psql -c 'CREATE DATABASE finance;' -U postgres
    - finance create_all
    - py.test -v tests --cov finance --cov-report term-missing
    - sonar-scanner

after_success:
  - coveralls

jobs:
  include:
    - stage: type checking
      python: "3.7"
      script:
        - pip install mypy
        - mypy --ignore-missing-imports finance
