sudo: false

language: python
python:
  - "3.6"

addons:
  postgresql: "9.4"
  sonarcloud:
    organization: "suminb-github"

services:
  - postgresql

env:
  global:
    - DB_URL="postgres:///finance"
    - TEST_DB_URL="postgres:///finance"
    - PYTHONPATH=.

jobs:
  include:
    - stage: type checking
      script:
        - pip install mypy
        - mypy --ignore-missing-imports finance
    - stage: build
      install:
        - pip install -r requirements.txt
        - pip install -r tests/requirements.txt
        - pip install -e .
      before_script:
        - psql -c 'CREATE DATABASE finance;' -U postgres
        - finance create_all
      script:
        - py.test -v tests --cov finance --cov-report term-missing
        - sonar-scanner
      after_success:
        - coveralls
    - stage: golang
      install:
        - export GOVERSION="1.12.4"
        - export GOPATH=$GOPATH:$(pwd)/go:$(pwd)/goport
        - export GOROOT=$(pwd)/go
        - export PATH=$GOROOT/bin:$PATH
        - curl -O "https://dl.google.com/go/go${GOVERSION}.linux-amd64.tar.gz"
        - tar zxf "go${GOVERSION}.linux-amd64.tar.gz"
        - go version
      before_script:
        - go get -v -t ./goport/src/finance
      script:
        - go test finance
