sudo: false

addons:
  postgresql: "9.4"
  sonarcloud:
    organization: "suminb-github"

services:
  - postgresql

env:
  global:
    - DB_URL="postgres:///finance"
    - TEST_DB_URL="postgres:///finance"
    - PYTHONPATH=.

matrix:
  include:
    - name: "Go build and test"
      language: go
      go:
        - 1.12.4
      before_script:
        - export GOPATH=$(pwd)/goport:$GOPATH
        - go version
        - go get -v -t ./goport/src/finance
      script:
        - go test finance

    - name: "Python type checking" 
      language: python 
      python:
        - 3.6
      script:
        - pip install mypy
        - mypy --ignore-missing-imports finance

    - name: "Python build and test"
      language: python 
      python:
        - 3.6
      install:
        - pip install -r requirements.txt
        - pip install -r tests/requirements.txt
        - pip install -e .
      before_script:
        - psql -c 'CREATE DATABASE finance;' -U postgres
        - finance create_all
      script:
        - py.test -v tests --cov finance --cov-report term-missing
        - sonar-scanner
      after_success:
        - coveralls
